name: Installation

on: [push]

jobs:

  Install:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] # , "macos-latest", "windows-latest"
        python-version: ["3.9"]

    steps:

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: cell2loc_env

      - name: Conda info
        shell: bash -el {0}
        run: conda info

      - name: Conda list
        shell: pwsh
        run: conda list

      - name: Inst
        shell: bash -el {0}
        run:  |
          conda activate cell2loc_env
          pip install cell2location[tutorials]

      - name: Test cell2location
        run: |
          import cell2location
        shell: python
